application: aire-de-jeux
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /static
  static_dir: static

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /admin/.*
  script: uploadVille.app
  login: admin

- url: /_ah/queue/importe_villes
  script: importe_villes.app
  login: admin

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /BingSiteAuth.xml
  static_files: static/BingSiteAuth.xml
  upload: static/BingSiteAuth.xml

- url: /liste/.*
  script: liste.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

